name: tfx_py2
channels:
  - defaults
dependencies:
  - yaml=
  - pip:
    - boto3==1.7.52
    - botocore==1.10.52
    - cachetools==2.1.0
    - configparser==3.5.0
    - docker==3.4.1
    - docker-pycreds==0.3.0
    - gitdb2==2.0.3
    - gitpython==2.1.10
    - google==2.0.1
    - google-auth==1.5.0
    - iml==0.6.1
    - ipaddress==1.0.22
    - jmespath==0.9.3
    - joblib==0.12.1
    - msgpack==0.5.6
    - nose-exclude==0.5.0
    - oauthlib==2.1.0
    - prometheus-client==0.3.0
    - protobuf==3.6.0
    - pyasn1==0.4.3
    - pyasn1-modules==0.2.2
    - querystring-parser==1.2.3
    - redis==2.10.6
    - requests-oauthlib==1.0.0
    - rsa==3.4.2
    - s3transfer==0.1.13
    - smmap2==2.0.3
    - tabulate==0.8.2
    - tqdm==4.23.4
    - uuid==1.30
    - websocket-client==0.48.0

